version: '3.8'

services:
  svg_to_video:
    build: ./svg_to_video
    container_name: svg_to_video
    ports:
      - "8000:8000"  
    restart: unless-stopped  
    environment:
      - ENV=production
    volumes:
      - generated_videos:/app/generated_videos  
    env_file:
      - .env

  svg_to_png:
    build: ./svg_to_png
    container_name: svg_to_png
    ports:
      - "8001:8001"  
    restart: unless-stopped
    environment:
      - ENV=production
    volumes:
      - generated_images:/app/generated_images
    env_file:
      - .env

volumes:
  generated_videos:
    driver: local 
  generated_images:
    driver: local