version: '3.8'

services:
  svg_to_video:
    build: ./svg_to_video
    container_name: svg_to_video
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    volumes:
      - ${GENERATED_VIDEOS_PATH}:/app/generated_videos

  svg_to_png:
    build: ./svg_to_png                 
    container_name: svg_to_png       
    ports:
      - "8001:8001"                    
    restart: always                   
    env_file:
      - .env              
    volumes:
      - ${GENERATED_IMAGES_PATH}:/app/generated_images

